production:
  url: <%= ENV['DATABASE_URL'] %>

development:
  adapter: postgresql
  encoding: unicode
  database: courses
  pool: 5
  host: localhost
  username: postgres
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: courses
  pool: 5
  host: localhost
  username: postgres
  password: password
