production:
  url: <%= ENV['DATABASE_URL'] %>

development:
  adapter: postgresql
  encoding: unicode
  database: courses
  pool: 5
  username: postgres
  password: M00d!nd!g0_

test:
  adapter: postgresql
  encoding: unicode
  database: courses
  pool: 5
  username: postgres
  password: M00d!nd!g0_
